name: Build/release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install dmg-license for macOS
        if: matrix.os == 'macos-latest'
        run: npm install dmg-license

      - name: Setup Python for macOS
        if: matrix.os == 'macos-latest'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build/release Electron app (Windows)
        if: matrix.os == 'windows-latest'
        env:
          BACKEND_URL: http://47.96.22.8:8005
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          EP_DRAFT: "false"
        run: npm run electron:build:win

      - name: Build/release Electron app (macOS)
        if: matrix.os == 'macos-latest'
        env:
          BACKEND_URL: http://47.96.22.8:8005
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          EP_DRAFT: "false"
          PYTHON_PATH: ${{ env.pythonLocation }}/bin/python3
        run: npm run electron:build:mac
